### ISSUE TITLE
Option to insert svg images as code

### ISSUE THREAD

**Issue by Vanderhoof** [foliant-docs/foliantcontrib.plantuml#3]
By default if we generate images in svg format they are inserted into document as images, hence the links don't work.

Suggestion is to add an option (for example `raw_svg: true`) to insert source code of svg-images directly into the markdown document.

Similar to the way graphviz preprocessor does it.

**Comment by anorm** [comment]
+1

**Comment by Vanderhoof** [comment]
Done in 1.0.7
